name: Fullback
configs:
  # issue https://gitlab.Fullback.id/Fullback-mobile/super-Fullback/-/issues/673
  Debug: debug
  Debug-IDE: debug
  Release (QA): release
  Release (AppStore): release
configFiles:
  Debug: xcconfig/Debug.xcconfig
  Debug-IDE: xcconfig/Debug.xcconfig
  Release (QA): xcconfig/Release.xcconfig
  Release (AppStore): xcconfig/Release-AppStore.xcconfig
settings:
  MARKETING_VERSION: 3.6.0
  CURRENT_PROJECT_VERSION: 1
targets:
  FullbackiOS:
    type: application
    platform: iOS
    postBuildScripts: []
    sources:
      - path: "FullbackiOS"
        includes:
          - "**/*.storyboard"
          - "**/*.xib"
          - "**/*.xcassets"
          - "**/*.strings"
          - "**/*.ttf"
          - "**/*.swift"
          - "**/*.json"
          - "**/*.h"
          - "**/*.m"
          - "**/*.html"
          - "**/*.bundle"
          - "**/*.xcdatamodeld"
          - "SSLPinning/*.der"
      - path: FullbackmacOS
        includes:
          - "Info.plist"
          - "*.entitlements"
        buildPhase: none
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "13.0"
      PRODUCT_MODULE_NAME: Fullback
      PRODUCT_BUNDLE_IDENTIFIER: $(APP_PRODUCT_BUNDLE_IDENTIFIER)
      INFOPLIST_FILE: FullbackiOS/Info.plist
      ENABLE_BITCODE: YES
    entitlements:
      path: FullbackiOS/Fullback.entitlements
      properties:
        aps-environment: development
    dependencies: []
  FullbackmacOS:
    type: application
    platform: macOS
    postBuildScripts: []
    sources:
      - path: "FullbackmacOS"
        includes:
          - "**/*.swift"
          - "**/*.xcassets"
      - path: FullbackmacOS
        includes:
          - "*.entitlements"
        buildPhase: none
    settings:
      OSX_DEPLOYMENT_TARGET: "10.15"
      PRODUCT_MODULE_NAME: Fullback
      PRODUCT_BUNDLE_IDENTIFIER: $(APP_PRODUCT_BUNDLE_IDENTIFIER)
      INFOPLIST_FILE: FullbackmacOS/Info.plist
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_IDENTITY: "-" #run locally
      PROVISIONING_PROFILE_SPECIFIER: ""
    entitlements:
      path: FullbackmacOS/FullbackmacOS.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.files.user-selected.read-only: true
    dependencies: []
schemes:
  FullbackiOS:
    build:
      targets:
        FullbackiOS: all
    run:
      config: Debug-IDE
    profile:
      config: Release (QA)
    analyze:
      config: Debug-IDE
    archive:
      config: Release (QA)